version: '2'
services:
  cms-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/cms/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cms
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
